FROM golang:1.25.0-alpine

WORKDIR /app

RUN apk add --no-cache git make gcc musl-dev curl bash
RUN git config --global --add safe.directory '*'

COPY go.mod go.sum ./
RUN go mod download

COPY makefile ./

RUN make install-deps

CMD ["sh", "-c", "make run"]